### ISSUE TITLE
Print message if external program (e.g. enca) not found.

### ISSUE THREAD

**Issue by konstunn** [s3rvac/AutoFenc#3]
That would be great if it printed such a message.

**Comment by s3rvac** [comment]
Thanks for the idea! In commit 530ad8c29e2b56a62388b3d859cd6587455d435f, I have added emission of warning messages when the external program is either not executable or its execution failed.

Note: As usual in this plugin, such messages are emitted only when `g:autofenc_emit_messages` is set (it is off by default).

**Comment by konstunn** [comment]
Please, make an emphasis in `README.md` that `g:autofence_emit_messages` should be set in `AutoFence.vim`, not in `vimrc` - for those who does not consider that obvious. And better yet I suggest settting this flag to `1` by default. I also suggest replacing all `echomsg` with simple `echo` not to be annoyed with "Press ENTER" all the time.

**Comment by s3rvac** [comment]
The `g:autofenc_emit_messages` option can (and should) be set in `.vimrc`:

```
let g:autofenc_emit_messages = 1
```

Generally, one should not modify plugins, but rather set options in `.vimrc`. Why would you want to set it in `AutoFenc.vim` rather than in `.vimrc`? Maybe you meant it vice versa?

As for setting this option to `1` by default, I am hesitant to do that. I find that this option is more useful during debugging (e.g. why is this encoding set?) rather than during day-to-day work. Also, other plugins rarely print messages. This makes `0` a better default value. However, maybe other people feel differently about this option?

As for replacing `echomsg` with `echo`, the problem with `echo` is twofold. First, it does not store the messages into `message-history`, so you cannot recall them after they disappear. Second, when multiple messages are emitted, you still have to press Enter to continue (well, depending on `cmdheight`). Again, I feel like `echomsg` is more appropriate, but if more people lean towards replacing it with `echo`, I will do that.

**Comment by konstunn** [comment]
Okay, this time so far let's hold over all the points of our discussion, except for emitting messages. The point is that setting `g:autofence_emit_messages` to `1` in `~/.vimrc` does not work for me. I even tried to place `let g:autofence_emit_messages = 1` before `execute pathogen#infect()`. Does not work, unfortunately. May be I should open another issue, shouldn't I?

**Comment by konstunn** [comment]
I have tried

``` shell
vim -D Unit1.pas
```

and found out that `AutoFence.vim` is executed after `~/.vimrc`. Don't know why it is so and, especially, how to fix it. This is why setting `g:autofence_emit_messages` to `1` does not take effect.

May be the issue is in the `AutoFence.vim`.

**Comment by konstunn** [comment]
Damn, the deal was in the **typo**.
Not `g:autofence_emit_messages` but `g:autofenc_emit_messages`.
Sorry.

**Comment by s3rvac** [comment]
That's OK. I am glad it is working for you now. If you encounter any other issues, let me know.
